<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="LiteDB" Version="5.0.21" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.4" />
    <PackageReference Include="NSwag.AspNetCore" Version="14.4.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\env.Vehicles.Infrastructure\eVN.Vehicles.Infrastructure.csproj" />
    <ProjectReference Include="..\enV.Vehicles.Services\eVN.Vehicles.Services.csproj" />
  </ItemGroup>

</Project>
